search-engine:
  version: alpha-v1
  
  crawler:
    start-url: "https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html"
    custom-url: "https://go.dev/doc/"
    crawl-limit: 2500
    min-workers: 1
    max-workers: 8

  database:
    storage-path: "../data/search_data.db"