search-engine:
  version: alpha-v1
  
  crawler:
    start-url: "https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html"
    custom-url: "https://wiki.archlinux.org/title/Main_page"
    crawl-limit: 600
    min-workers: 1
    max-workers: 8
    damping: 0.85
    iterations: 30

  database:
    storage-path: "../data/search_data.db"