search-engine:
  version: alpha-v1
  
  cralwer:
    start-url: "https://people.scs.carleton.ca/~avamckenney/fruitsA/N-0.html"
    custom-url: 
    CRAWL_LIMIT: 2500

  database:
    storage-path: SearchEngine/data/search_data.db